# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Converter' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Converter
  pod 'RMHttp'
  pod 'SVProgressHUD'
  pod 'ActionSheetPicker-3.0'

end
